name: Build Linux Executable

permissions:
  contents: write

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgles2-mesa-dev libx11-dev xorg-dev gcc libvulkan-dev
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install Go dependencies
        run: |
          go get gioui.org@v0.8.0
          go get gioui.org/app@v0.8.0
          go get gioui.org/layout@v0.8.0
          go get gioui.org/op@v0.8.0
          go get gioui.org/op/clip@v0.8.0
          go get gioui.org/op/paint@v0.8.0
          go get gioui.org/text@v0.8.0
          go get gioui.org/unit@v0.8.0
          go get gioui.org/widget@v0.8.0
          go get gioui.org/widget/material@v0.8.0
          go get github.com/PuerkitoBio/goquery@v1.8.1
          go get github.com/google/uuid@v1.6.0
          go get github.com/ncruces/zenity@v0.10.0
          go mod tidy

      - name: Install UPX
        run: |
          sudo apt-get install -y upx-ucl

      - name: Build and compress
        run: |
          go build -ldflags="-s -w" -o mhtml-extractor
          upx --best mhtml-extractor

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mhtml-extractor-linux
          path: mhtml-extractor

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: mhtml-extractor
          body: |
            MHTML File Extractor release for Linux (amd64).
            Features:
            - Parse MHTML files and extract embedded resources (images, CSS, JavaScript).
            - View raw HTML content.
            - Toggle external JavaScript fetching with concurrent downloads.
            - Extract selected resources to a specified directory.
            - Switch between dark and light themes.

            **macOS Users**: Due to Gio’s Xcode dependency, macOS builds are not included. If you’ve built the `mhtml-extractor` binary for macOS (amd64), please share it via a fast file transfer service (e.g., [WeTransfer](https://wetransfer.com), [TransferNow](https://www.transfernow.net)) to [your-email@example.com](mailto:your-email@example.com) or open an issue/pull request. Your binary will be added to this release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
